config/routes.rb
Rails.application.routes.draw do
  resources :web_scrappers

  get "download", to: 'web_scrappers#download', as: :download
  root 'web_scrappers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/web_scrapper.rb
require 'kimurai'

class WebScrapper < Kimurai::Base
  @name = "web_scrapper_spider"
  @engine = :selenium_chrome
  @start_urls = ["https://metaruby.com/"]
  @config = {
      user_agent: "Chrome/68.0.3440.84"
    }

  attr_accessor :blogs

  def parse(response, url:, data: { })
    @blogs = []
    posts_headers_path = "//table[@class='topic-list ember-view']//tbody//tr"
    count = response.xpath(posts_headers_path).count
    
    loop do
      browser.execute_script("window.scrollBy(0,10000)") ; sleep 2
      response = browser.current_response

      new_count = response.xpath(posts_headers_path).count
      if count == new_count
        parse_data(response)
        logger.info "> Pagination is done" and break
      else
        count = new_count
        logger.info "> Continue scrolling, current count is #{count}..."
      end
    end
    
    logger.info "> Data saved to results.json"
  end

  def parse_data(response)
    response.xpath("//table[@class='topic-list ember-view']//tbody//tr").each do |tr|
      scrapped_data = {
                        title: tr.at('td[1]//span').text,
                        category: tr.at('td[1]//div//span').text,
                        date: tr.at('td[3]').text.strip
                      }
      blogs << scrapped_data
      save_to "results.json", scrapped_data.as_json, format: :json
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/web_scrappers_controller.rb
class WebScrappersController < ApplicationController
  def index
  end

  def new
    WebScrapper.crawl! 
    redirect_to root_path, notice: 'Results stored in results.json file.'
  end

  def download
    send_file(
      "#{Rails.root}/results.json",
      filename: "scraping_data.json",
      type: "application/json"
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web_scrappers_helper.rb
module WebScrappersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebScrappingDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/web_scrappers/index.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>

<h1>WebScrappers#index</h1>

<% if File.exists?(Rails.root.join('results.json')) %>
  <p>You can download the file here</p>
  <%= link_to 'Results', download_path %>
<% end %>
<br>
<br>
<%= link_to 'Start Scrap', new_web_scrapper_path %>